services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: salescalc-api-dev
    command: [ "sh", "-c", "npx prisma generate && npx prisma db push && npm run dev" ]
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    ports:
      - "3000:3000"

  frontend:
    image: python:3.9-slim
    container_name: salescalc-web-dev
    working_dir: /app
    volumes:
      - .:/app
    command: [ "python3", "-m", "http.server", "80" ]
    depends_on:
      - backend
    ports:
      - "8000:80"
